services:
  grammar-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=3000
      - APP_HOST=${APP_HOST}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:${APP_PORT},http://127.0.0.1:${APP_PORT}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${APP_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  redis-loader:
    build:
      context: .
      dockerfile: Dockerfile.redis-loader
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      redis:
        condition: service_healthy
    restart: "no"

volumes:
  redis-data: